{lib}: {
  username = "toshi";
  userfullname = "austrolopithecus";
  useremail = "ga.czsan@gmail.com";
  # generated by `mkpasswd -m scrypt`
  initialHashedPassword = "$7$CU..../....UdV9pQJUxNwSN2SXH.2CY0$6viS2fYvADyc5ezRoYKAovgK.dHF3P8Jn5Ewa1NPUY7";
  sshAuthorizedKeys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGDvLTNg1MZSXIsQsndo1DI+HAwClfAlvZIuN1pHbzSj toshi@ronaldinhosoccer"
  ];
}
