# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ehci_pci" "nvme" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [
    "vfio_pci"
    "vfio"
    "vfio_iommu_type1"
  ];
  boot.kernelModules = ["kvm-intel" "v4l2loopback"];
  boot.extraModulePackages = [pkgs.linuxPackages.v4l2loopback];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/d56336a7-79ed-4b73-8f59-a8a9b22fc676";
    fsType = "btrfs";
    options = ["subvol=rootfs"];
  };

  fileSystems."/.swapvol" = {
    device = "/dev/disk/by-uuid/d56336a7-79ed-4b73-8f59-a8a9b22fc676";
    fsType = "btrfs";
    options = ["subvol=swap"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/9932-BD2F";
    fsType = "vfat";
    options = ["fmask=0022" "dmask=0022"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/d56336a7-79ed-4b73-8f59-a8a9b22fc676";
    fsType = "btrfs";
    options = ["subvol=home"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/d56336a7-79ed-4b73-8f59-a8a9b22fc676";
    fsType = "btrfs";
    options = ["subvol=nix"];
  };

  fileSystems."/partition-root" = {
    device = "/dev/disk/by-uuid/d56336a7-79ed-4b73-8f59-a8a9b22fc676";
    fsType = "btrfs";
  };

  swapDevices = [];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp7s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
